<?php
/**
 * D8 Cluster 1 — pre-ported core tool inventory manifest.
 *
 * Maps each tool slug to its nvoos/core (or wordpress-adapter)
 * implementation FQCN plus the ordered dependency keys the class
 * constructor expects (resolved by CoreToolFactory). Generated
 * 2026-09-05 from lib/core/src/Tool + lib/wordpress-adapter/src/Tool
 * (EvolveHarnessTool excluded — platform-owned, Cluster 3;
 * LegacyToolAdapter excluded — adapter wrapper, not a tool;
 * seven base-coupled adapter tools excluded — Cluster 2 hardening:
 * VectorizeImageTool, MediaLibraryOptimizerTool,
 * RunGeminiManagedAgentTool, DelegateToA2aAgentTool, ProbeChatTool,
 * QueryMeshIntelligentTool, VisualizeWorkflowMetricsTool).
 *
 * @package NvoosContentGraphAi\Tools
 * @since   1.0.4
 */

declare(strict_types=1);

namespace NvoosContentGraphAi\Tools;

final class CoreToolManifest {

	/**
	 * @return array<string,array{0:string,1:array<int,string>}>
	 */
	public static function manifest(): array {
		// phpcs:disable WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned -- Generated one-line slug tuples; aligning 203 entries of varying slug length would triple the file without aiding review.
		return array(
			'aggregate_agent_results' => array( 'Nvoos\WordPress\Tool\AggregateAgentResultsTool', array( 'errors' ) ),
			'analyze_code_sequence' => array( 'Nvoos\Core\Tool\AnalyzeCodeSequenceTool', array( 'errors' ) ),
			'analyze_comment_content' => array( 'Nvoos\Core\Tool\AnalyzeCommentContentTool', array( 'errors' ) ),
			'analyze_file_suitability' => array( 'Nvoos\Core\Tool\AnalyzeFileSuitabilityTool', array( 'errors' ) ),
			'analyze_image' => array( 'Nvoos\Core\Tool\AnalyzeImageTool', array( 'errors' ) ),
			'analyze_video' => array( 'Nvoos\Core\Tool\AnalyzeVideoTool', array( 'errors' ) ),
			'auto_categorize_content' => array( 'Nvoos\Core\Tool\AutoCategorizeContentTool', array( 'errors' ) ),
			'base64' => array( 'Nvoos\Core\Tool\Base64Tool', array( 'errors' ) ),
			'batch_embed_content' => array( 'Nvoos\Core\Tool\BatchEmbedContentTool', array( 'errors' ) ),
			'calculate_erlang_c' => array( 'Nvoos\Core\Tool\CalculateErlangCTool', array( 'errors', 'erlang' ) ),
			'cancel_job' => array( 'Nvoos\Core\Tool\CancelJobTool', array( 'errors', 'queue' ) ),
			'check_capability' => array( 'Nvoos\Core\Tool\CheckCapabilityTool', array( 'errors', 'auth' ) ),
			'check_video_status' => array( 'Nvoos\Core\Tool\CheckVideoStatusTool', array( 'errors', 'queue' ) ),
			'check_workflow_health' => array( 'Nvoos\Core\Tool\CheckWorkflowHealthTool', array( 'errors', 'agent' ) ),
			'client_analyze_sentiment' => array( 'Nvoos\Core\Tool\ClientAnalyzeSentimentTool', array( 'errors' ) ),
			'client_extract_entities' => array( 'Nvoos\Core\Tool\ClientExtractEntitiesTool', array( 'errors' ) ),
			'client_question_answering' => array( 'Nvoos\Core\Tool\ClientQuestionAnsweringTool', array( 'errors' ) ),
			'client_semantic_search' => array( 'Nvoos\Core\Tool\ClientSemanticSearchTool', array( 'errors' ) ),
			'client_summarize_text' => array( 'Nvoos\Core\Tool\ClientSummarizeTextTool', array( 'errors' ) ),
			'client_translate_text' => array( 'Nvoos\Core\Tool\ClientTranslateTextTool', array( 'errors' ) ),
			'color_convert' => array( 'Nvoos\Core\Tool\ColorConvertTool', array( 'errors' ) ),
			'content_freshness_checker' => array( 'Nvoos\Core\Tool\ContentFreshnessCheckerTool', array( 'errors' ) ),
			'content_recommendation_engine' => array( 'Nvoos\Core\Tool\ContentRecommendationEngineTool', array( 'errors' ) ),
			'convert_image_format' => array( 'Nvoos\Core\Tool\ConvertImageFormatTool', array( 'errors', 'img' ) ),
			'count_posts' => array( 'Nvoos\Core\Tool\CountPostsTool', array( 'errors', 'content' ) ),
			'count_tokens' => array( 'Nvoos\Core\Tool\CountTokensTool', array( 'errors' ) ),
			'crawl4ai_price_lookup' => array( 'Nvoos\Core\Tool\Crawl4AiPriceLookupTool', array( 'errors', 'settings', 'http' ) ),
			'create_agent_team' => array( 'Nvoos\Core\Tool\CreateAgentTeamTool', array( 'errors', 'agent' ) ),
			'create_assistant' => array( 'Nvoos\WordPress\Tool\CreateAssistantTool', array( 'errors' ) ),
			'create_assistant_validated' => array( 'Nvoos\WordPress\Tool\CreateAssistantValidatedTool', array( 'errors' ) ),
			'create_batch' => array( 'Nvoos\Core\Tool\CreateBatchTool', array( 'errors', 'settings', 'http' ) ),
			'create_chart' => array( 'Nvoos\Core\Tool\CreateChartTool', array( 'errors' ) ),
			'create_chart_validated' => array( 'Nvoos\Core\Tool\CreateChartValidatedTool', array( 'errors' ) ),
			'create_cron_job' => array( 'Nvoos\Core\Tool\CreateCronJobTool', array( 'errors', 'queue' ) ),
			'create_cron_job_validated' => array( 'Nvoos\Core\Tool\CreateCronJobValidatedTool', array( 'errors', 'queue' ) ),
			'create_image_variation' => array( 'Nvoos\Core\Tool\CreateImageVariationTool', array( 'errors', 'settings', 'http' ) ),
			'create_post' => array( 'Nvoos\Core\Tool\CreatePostTool', array( 'errors', 'content' ) ),
			'create_post_validated' => array( 'Nvoos\Core\Tool\CreatePostValidatedTool', array( 'errors', 'content' ) ),
			'create_text_embeddings' => array( 'Nvoos\Core\Tool\CreateTextEmbeddingsTool', array( 'errors', 'settings', 'http' ) ),
			'create_vector_store' => array( 'Nvoos\Core\Tool\CreateVectorStoreTool', array( 'errors', 'settings', 'http' ) ),
			'crop_image' => array( 'Nvoos\Core\Tool\CropImageTool', array( 'errors', 'img' ) ),
			'deep_research' => array( 'Nvoos\Core\Tool\DeepResearchTool', array( 'errors', 'settings' ) ),
			'delegate_to_agent' => array( 'Nvoos\Core\Tool\DelegateToAgentTool', array( 'errors', 'agent' ) ),
			'delete_cache' => array( 'Nvoos\Core\Tool\DeleteCacheTool', array( 'errors', 'cache' ) ),
			'delete_cron_job' => array( 'Nvoos\Core\Tool\DeleteCronJobTool', array( 'errors', 'queue' ) ),
			'delete_file' => array( 'Nvoos\Core\Tool\DeleteFileTool', array( 'errors', 'files' ) ),
			'delete_post' => array( 'Nvoos\Core\Tool\DeletePostTool', array( 'errors', 'content' ) ),
			'delete_setting' => array( 'Nvoos\Core\Tool\DeleteSettingTool', array( 'errors', 'settings' ) ),
			'dispatch_event' => array( 'Nvoos\Core\Tool\DispatchEventTool', array( 'errors', 'events' ) ),
			'edit_gemini_image' => array( 'Nvoos\Core\Tool\EditGeminiImageTool', array( 'errors', 'settings', 'http' ) ),
			'edit_gemini_image_validated' => array( 'Nvoos\Core\Tool\EditGeminiImageValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'edit_omni_video' => array( 'Nvoos\Core\Tool\EditOmniVideoTool', array( 'errors', 'settings', 'http' ) ),
			'edit_openai_image' => array( 'Nvoos\Core\Tool\EditOpenAIImageTool', array( 'errors', 'settings', 'http' ) ),
			'enqueue_job' => array( 'Nvoos\Core\Tool\EnqueueJobTool', array( 'errors', 'queue' ) ),
			'erlang_c_concurrency_advisor' => array( 'Nvoos\Core\Tool\ErlangCConcurrencyAdvisorTool', array( 'errors', 'erlang', 'settings' ) ),
			'erlang_c_queue_health' => array( 'Nvoos\Core\Tool\ErlangCQueueHealthTool', array( 'errors', 'erlang', 'settings', 'http' ) ),
			'erlang_c_staffing_advisor' => array( 'Nvoos\Core\Tool\ErlangCStaffingAdvisorTool', array( 'errors', 'erlang', 'settings', 'http' ) ),
			'execute_workflow' => array( 'Nvoos\Core\Tool\ExecuteWorkflowTool', array( 'errors', 'agent' ) ),
			'extract_domain' => array( 'Nvoos\Core\Tool\ExtractDomainTool', array( 'errors' ) ),
			'extract_image_text' => array( 'Nvoos\Core\Tool\ExtractImageTextTool', array( 'errors' ) ),
			'format_bytes' => array( 'Nvoos\Core\Tool\FormatBytesTool', array( 'errors' ) ),
			'format_date' => array( 'Nvoos\Core\Tool\FormatDateTool', array( 'errors' ) ),
			'gemini_geospatial_query' => array( 'Nvoos\Core\Tool\GeminiGeospatialQueryTool', array( 'errors', 'settings', 'http' ) ),
			'generate_auth0_token' => array( 'Nvoos\Core\Tool\GenerateAuth0TokenTool', array( 'errors', 'settings', 'http' ) ),
			'generate_chart' => array( 'Nvoos\Core\Tool\GenerateChartTool', array( 'errors' ) ),
			'generate_cloudflareai_image' => array( 'Nvoos\Core\Tool\GenerateCloudflareAIImageTool', array( 'errors', 'settings', 'http' ) ),
			'generate_gemini_image' => array( 'Nvoos\Core\Tool\GenerateGeminiImageTool', array( 'errors', 'settings', 'http' ) ),
			'generate_gemini_image_validated' => array( 'Nvoos\Core\Tool\GenerateGeminiImageValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'generate_image_alt_text' => array( 'Nvoos\Core\Tool\GenerateImageAltTextTool', array( 'errors' ) ),
			'generate_image_alt_text_validated' => array( 'Nvoos\Core\Tool\GenerateImageAltTextValidatedTool', array( 'errors' ) ),
			'generate_image_caption' => array( 'Nvoos\Core\Tool\GenerateImageCaptionTool', array( 'errors' ) ),
			'generate_image_caption_validated' => array( 'Nvoos\Core\Tool\GenerateImageCaptionValidatedTool', array( 'errors' ) ),
			'generate_mermaid' => array( 'Nvoos\Core\Tool\GenerateMermaidTool', array( 'errors' ) ),
			'generate_music' => array( 'Nvoos\Core\Tool\GenerateMusicTool', array( 'errors', 'settings', 'http' ) ),
			'generate_music_validated' => array( 'Nvoos\Core\Tool\GenerateMusicValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'generate_omni_video' => array( 'Nvoos\Core\Tool\GenerateOmniVideoTool', array( 'errors', 'settings', 'http' ) ),
			'generate_openai_image' => array( 'Nvoos\Core\Tool\GenerateOpenAIImageTool', array( 'errors', 'settings', 'http' ) ),
			'generate_openai_image_validated' => array( 'Nvoos\Core\Tool\GenerateOpenAIImageValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'generate_openai_speech' => array( 'Nvoos\Core\Tool\GenerateOpenAISpeechTool', array( 'errors', 'settings', 'http' ) ),
			'generate_openai_speech_validated' => array( 'Nvoos\Core\Tool\GenerateOpenAISpeechValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'generate_post_excerpt' => array( 'Nvoos\Core\Tool\GeneratePostExcerptTool', array( 'errors' ) ),
			'generate_simple_jwt_token' => array( 'Nvoos\Core\Tool\GenerateSimpleJWTTokenTool', array( 'errors' ) ),
			'generate_slug' => array( 'Nvoos\Core\Tool\GenerateSlugTool', array( 'errors' ) ),
			'generate_sora_video' => array( 'Nvoos\Core\Tool\GenerateSoraVideoTool', array( 'errors', 'settings', 'http' ) ),
			'generate_sora_video_validated' => array( 'Nvoos\Core\Tool\GenerateSoraVideoValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'generate_uuid' => array( 'Nvoos\Core\Tool\GenerateUuidTool', array( 'errors' ) ),
			'generate_veo_video' => array( 'Nvoos\Core\Tool\GenerateVeoVideoTool', array( 'errors', 'settings', 'http' ) ),
			'generate_veo_video_validated' => array( 'Nvoos\Core\Tool\GenerateVeoVideoValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'generate_video_caption' => array( 'Nvoos\Core\Tool\GenerateVideoCaptionTool', array( 'errors' ) ),
			'geocode_address' => array( 'Nvoos\Core\Tool\GeocodeAddressTool', array( 'errors', 'settings', 'http' ) ),
			'get_batch_status' => array( 'Nvoos\Core\Tool\GetBatchStatusTool', array( 'errors', 'settings', 'http' ) ),
			'get_cache' => array( 'Nvoos\Core\Tool\GetCacheTool', array( 'errors', 'cache' ) ),
			'get_cron_job' => array( 'Nvoos\Core\Tool\GetCronJobTool', array( 'errors', 'queue' ) ),
			'get_current_user' => array( 'Nvoos\Core\Tool\GetCurrentUserTool', array( 'errors', 'auth' ) ),
			'get_file_info' => array( 'Nvoos\Core\Tool\GetFileInfoTool', array( 'errors', 'files' ) ),
			'get_gdacs_events' => array( 'Nvoos\Core\Tool\GetGdacsEventsTool', array( 'errors', 'http' ) ),
			'get_job_status' => array( 'Nvoos\Core\Tool\GetJobStatusTool', array( 'errors', 'queue' ) ),
			'get_model_information' => array( 'Nvoos\Core\Tool\GetModelInformationTool', array( 'errors', 'settings', 'http' ) ),
			'get_nhc_active_storms' => array( 'Nvoos\Core\Tool\GetNhcActiveStormsTool', array( 'errors', 'http' ) ),
			'get_open_meteo_forecast' => array( 'Nvoos\Core\Tool\GetOpenMeteoForecastTool', array( 'errors', 'http' ) ),
			'get_openai_file_details' => array( 'Nvoos\Core\Tool\GetOpenAIFileDetailsTool', array( 'errors', 'settings', 'http' ) ),
			'get_post' => array( 'Nvoos\Core\Tool\GetPostTool', array( 'errors', 'content' ) ),
			'get_post_meta' => array( 'Nvoos\Core\Tool\GetPostMetaTool', array( 'errors', 'content' ) ),
			'get_post_taxonomies' => array( 'Nvoos\Core\Tool\GetPostTaxonomiesTool', array( 'errors', 'content' ) ),
			'get_post_type_schema' => array( 'Nvoos\Core\Tool\GetPostTypeSchemaTool', array( 'errors', 'schema' ) ),
			'get_profession' => array( 'Nvoos\Core\Tool\GetProfessionTool', array( 'errors', 'profession' ) ),
			'get_recent_posts' => array( 'Nvoos\Core\Tool\GetRecentPostsTool', array( 'errors', 'content' ) ),
			'get_recent_posts_validated' => array( 'Nvoos\Core\Tool\GetRecentPostsValidatedTool', array( 'errors', 'content' ) ),
			'get_setting' => array( 'Nvoos\Core\Tool\GetSettingTool', array( 'errors', 'settings' ) ),
			'get_site_summary' => array( 'Nvoos\Core\Tool\GetSiteSummaryTool', array( 'errors', 'settings' ) ),
			'get_user_info' => array( 'Nvoos\Core\Tool\GetUserInfoTool', array( 'errors', 'auth' ) ),
			'get_vector_store' => array( 'Nvoos\Core\Tool\GetVectorStoreTool', array( 'errors', 'settings', 'http' ) ),
			'hash_string' => array( 'Nvoos\Core\Tool\HashStringTool', array( 'errors' ) ),
			'huggingface_dataset_filter' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetFilterTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_get_info' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetGetInfoTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_get_parquet' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetGetParquetTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_get_rows' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetGetRowsTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_get_size' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetGetSizeTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_get_statistics' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetGetStatisticsTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_is_valid' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetIsValidTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_list_splits' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetListSplitsTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_preview_rows' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetPreviewRowsTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_dataset_search' => array( 'Nvoos\Core\Tool\HuggingFaceDatasetSearchTool', array( 'errors', 'settings', 'http' ) ),
			'huggingface_recommended_datasets' => array( 'Nvoos\Core\Tool\HuggingFaceRecommendedDatasetsTool', array( 'errors', 'settings', 'http' ) ),
			'image_alt_text_optimizer' => array( 'Nvoos\WordPress\Tool\ImageAltTextOptimizerTool', array( 'errors' ) ),
			'image_format_batch_converter' => array( 'Nvoos\WordPress\Tool\ImageFormatBatchConverterTool', array( 'errors' ) ),
			'increment_cache' => array( 'Nvoos\Core\Tool\IncrementCacheTool', array( 'errors', 'cache' ) ),
			'list_available_models' => array( 'Nvoos\Core\Tool\ListAvailableModelsTool', array( 'errors', 'settings', 'http' ) ),
			'list_batches' => array( 'Nvoos\Core\Tool\ListBatchesTool', array( 'errors', 'settings', 'http' ) ),
			'list_cron_jobs' => array( 'Nvoos\Core\Tool\ListCronJobsTool', array( 'errors', 'queue' ) ),
			'list_jobs' => array( 'Nvoos\Core\Tool\ListJobsTool', array( 'errors', 'queue' ) ),
			'list_openai_files' => array( 'Nvoos\Core\Tool\ListOpenAIFilesTool', array( 'errors', 'settings', 'http' ) ),
			'list_professions' => array( 'Nvoos\Core\Tool\ListProfessionsTool', array( 'errors', 'profession' ) ),
			'list_settings' => array( 'Nvoos\Core\Tool\ListSettingsTool', array( 'errors', 'settings' ) ),
			'list_skills' => array( 'Nvoos\Core\Tool\ListSkillsTool', array( 'errors', 'skills' ) ),
			'list_vector_stores' => array( 'Nvoos\Core\Tool\ListVectorStoresTool', array( 'errors', 'settings', 'http' ) ),
			'load_skill' => array( 'Nvoos\Core\Tool\LoadSkillTool', array( 'errors', 'skills' ) ),
			'manage_context_lifecycle' => array( 'Nvoos\Core\Tool\ManageContextLifecycleTool', array( 'errors', 'memory' ) ),
			'manage_vector_store_files' => array( 'Nvoos\Core\Tool\ManageVectorStoreFilesTool', array( 'errors', 'settings', 'http' ) ),
			'math_eval' => array( 'Nvoos\Core\Tool\MathEvalTool', array( 'errors' ) ),
			'merge_arrays' => array( 'Nvoos\Core\Tool\MergeArraysTool', array( 'errors' ) ),
			'mine_agent_memory' => array( 'Nvoos\Core\Tool\MineAgentMemoryTool', array( 'errors', 'memory' ) ),
			'moderate_content' => array( 'Nvoos\Core\Tool\ModerateContentTool', array( 'errors', 'settings', 'http' ) ),
			'monitor_batch' => array( 'Nvoos\Core\Tool\MonitorBatchTool', array( 'errors', 'settings', 'http' ) ),
			'open_openai_logs' => array( 'Nvoos\Core\Tool\OpenOpenAILogsTool', array( 'errors', 'settings', 'http' ) ),
			'parse_csv' => array( 'Nvoos\Core\Tool\ParseCsvTool', array( 'errors' ) ),
			'performance_optimizer_assistant' => array( 'Nvoos\WordPress\Tool\PerformanceOptimizerAssistantTool', array( 'errors' ) ),
			'probe_remote_mcp' => array( 'Nvoos\Core\Tool\ProbeRemoteMcpTool', array( 'errors', 'http' ) ),
			'profession_stats' => array( 'Nvoos\Core\Tool\ProfessionStatsTool', array( 'errors', 'profession' ) ),
			'purge_cache' => array( 'Nvoos\Core\Tool\PurgeCacheTool', array( 'errors', 'settings', 'http' ) ),
			'purge_cloudflare_cache' => array( 'Nvoos\Core\Tool\PurgeCloudflareCacheTool', array( 'errors', 'settings', 'http' ) ),
			'purge_varnish_cache' => array( 'Nvoos\Core\Tool\PurgeVarnishCacheTool', array( 'errors', 'settings', 'http' ) ),
			'query_remote_site' => array( 'Nvoos\Core\Tool\QueryRemoteSiteTool', array( 'errors', 'settings', 'http' ) ),
			'recall_memory' => array( 'Nvoos\Core\Tool\RecallMemoryTool', array( 'errors', 'memory' ) ),
			'reliefweb_reports' => array( 'Nvoos\Core\Tool\ReliefwebReportsTool', array( 'errors', 'http' ) ),
			'resize_image' => array( 'Nvoos\Core\Tool\ResizeImageTool', array( 'errors', 'img' ) ),
			'retrieve_agent_memory' => array( 'Nvoos\Core\Tool\RetrieveAgentMemoryTool', array( 'errors', 'memory' ) ),
			'rotate_image' => array( 'Nvoos\Core\Tool\RotateImageTool', array( 'errors', 'img' ) ),
			'run_crawl4ai_job' => array( 'Nvoos\Core\Tool\RunCrawl4AiJobTool', array( 'errors', 'settings', 'http' ) ),
			'run_openai_external_action' => array( 'Nvoos\Core\Tool\RunOpenAIExternalActionTool', array( 'errors', 'settings', 'http' ) ),
			'save_post' => array( 'Nvoos\Core\Tool\SavePostTool', array( 'errors', 'content' ) ),
			'save_post_validated' => array( 'Nvoos\Core\Tool\SavePostValidatedTool', array( 'errors', 'content' ) ),
			'save_profession' => array( 'Nvoos\Core\Tool\SaveProfessionTool', array( 'errors', 'profession' ) ),
			'schedule_job' => array( 'Nvoos\Core\Tool\ScheduleJobTool', array( 'errors', 'queue' ) ),
			'search_attachments' => array( 'Nvoos\Core\Tool\SearchAttachmentsTool', array( 'errors', 'files' ) ),
			'search_content' => array( 'Nvoos\Core\Tool\SearchContentTool', array( 'errors', 'content' ) ),
			'search_content_validated' => array( 'Nvoos\Core\Tool\SearchContentValidatedTool', array( 'errors', 'content' ) ),
			'search_drive' => array( 'Nvoos\Core\Tool\SearchDriveTool', array( 'errors', 'settings', 'http' ) ),
			'search_gmail' => array( 'Nvoos\Core\Tool\SearchGmailTool', array( 'errors', 'settings', 'http' ) ),
			'search_places' => array( 'Nvoos\Core\Tool\SearchPlacesTool', array( 'errors', 'settings', 'http' ) ),
			'semantic_content_search' => array( 'Nvoos\Core\Tool\SemanticContentSearchTool', array( 'errors', 'memory' ) ),
			'semantic_context_search' => array( 'Nvoos\Core\Tool\SemanticContextSearchTool', array( 'errors', 'memory' ) ),
			'send_group_email' => array( 'Nvoos\Core\Tool\SendGroupEmailTool', array( 'errors', 'email' ) ),
			'send_group_email_validated' => array( 'Nvoos\Core\Tool\SendGroupEmailValidatedTool', array( 'errors', 'email' ) ),
			'seo_meta_optimizer' => array( 'Nvoos\Core\Tool\SEOMetaOptimizerTool', array( 'errors' ) ),
			'set_cache' => array( 'Nvoos\Core\Tool\SetCacheTool', array( 'errors', 'cache' ) ),
			'store_agent_context' => array( 'Nvoos\Core\Tool\StoreAgentContextTool', array( 'errors', 'memory' ) ),
			'strip_html' => array( 'Nvoos\Core\Tool\StripHtmlTool', array( 'errors' ) ),
			'suggest_best_model' => array( 'Nvoos\Core\Tool\SuggestBestModelTool', array( 'errors' ) ),
			'suggest_internal_links' => array( 'Nvoos\Core\Tool\SuggestInternalLinksTool', array( 'errors' ) ),
			'time_ago' => array( 'Nvoos\Core\Tool\TimeAgoTool', array( 'errors' ) ),
			'transcribe_openai_audio' => array( 'Nvoos\Core\Tool\TranscribeOpenAIAudioTool', array( 'errors', 'settings', 'http' ) ),
			'transcribe_openai_audio_validated' => array( 'Nvoos\Core\Tool\TranscribeOpenAIAudioValidatedTool', array( 'errors', 'settings', 'http' ) ),
			'truncate_text' => array( 'Nvoos\Core\Tool\TruncateTextTool', array( 'errors' ) ),
			'unschedule_job' => array( 'Nvoos\Core\Tool\UnscheduleJobTool', array( 'errors', 'queue' ) ),
			'update_post' => array( 'Nvoos\Core\Tool\UpdatePostTool', array( 'errors', 'content' ) ),
			'update_setting' => array( 'Nvoos\Core\Tool\UpdateSettingTool', array( 'errors', 'settings' ) ),
			'upload_file' => array( 'Nvoos\Core\Tool\UploadFileTool', array( 'errors', 'files' ) ),
			'validate_json' => array( 'Nvoos\Core\Tool\ValidateJsonTool', array( 'errors' ) ),
			'validate_reasoning_chain' => array( 'Nvoos\Core\Tool\ValidateReasoningChainTool', array( 'errors' ) ),
			'validate_workflow' => array( 'Nvoos\Core\Tool\ValidateWorkflowTool', array( 'errors' ) ),
			'vision_object_localization' => array( 'Nvoos\Core\Tool\VisionObjectLocalizationTool', array( 'errors' ) ),
			'vision_product_search' => array( 'Nvoos\Core\Tool\VisionProductSearchTool', array( 'errors' ) ),
			'wait_for_user' => array( 'Nvoos\Core\Tool\WaitForUserTool', array( 'errors' ) ),
			'web_search' => array( 'Nvoos\Core\Tool\WebSearchTool', array( 'errors', 'settings', 'http' ) ),
			'web_search_validated' => array( 'Nvoos\Core\Tool\WebSearchValidatedTool', array( 'errors', 'settings', 'http' ) ),
		);
		// phpcs:enable WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned
	}
}
